FROM node:10 AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .

FROM node:10-alpine
WORKDIR /app
COPY --from=builder /app ./

EXPOSE 8400:8400


CMD ["npm", "run", "start"]