---

name: Build and push a docker image
on:
  workflow_dispatch:
  push:
    branches: ['feature/*', 'dev']
jobs:
  test-code:
    name: "--- Run tests ---"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Unit Test
        run: npm run test
