---

name: Build and push a docker image
on:
  workflow_dispatch:
  push:
    branches: ['main']
jobs:
  test-code:
    name: "--- Run tests ---"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Unit Test
        run: npm run test

  ######################
  # --- Docker Hub --- #
  ######################
  docker-hub:
    name: "--- Docker Hub ---"
    runs-on: ubuntu-18.04
    needs: [test-code]
    steps:
      - name: Set env
        run: echo "REPO=${{ secrets.DOCKER_USER }}/${GITHUB_REPOSITORY#*\/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: >
          docker build
          -t $REPO:production
          -t $REPO:${{ github.sha  }}
          --build-arg NODE_ENV=${{ secrets.NODE_ENV }}
          --build-arg PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          --build-arg PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
          --build-arg PGHOST=${{ secrets.PGHOST }}
          --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          --build-arg POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          --build-arg KONG=${{ secrets.KONG }}
          .

      - name: Publish Docker sha
        run: docker push $REPO:${{ github.sha }}

      - name: Publish Docker image production
        run: docker push $REPO:production

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker-hub]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_PROD_URL }}